-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 06, 2022 at 08:17 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.0.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `postwp`
--

-- --------------------------------------------------------

--
-- Table structure for table `laporan_wp_1`
--

CREATE TABLE `laporan_wp_1` (
  `id` bigint(20) NOT NULL DEFAULT 0,
  `judul` varchar(150) DEFAULT NULL,
  `nama_gambar` varchar(100) NOT NULL,
  `kunci` varchar(50) DEFAULT NULL,
  `url` varchar(200) DEFAULT NULL,
  `url_x` varchar(200) DEFAULT NULL,
  `url_preview` varchar(200) DEFAULT NULL,
  `url_asli` varchar(200) DEFAULT NULL,
  `url_asli_preview` varchar(200) DEFAULT NULL,
  `harga` int(11) DEFAULT NULL,
  `tags` varchar(250) DEFAULT NULL,
  `mega_link` varchar(100) DEFAULT NULL,
  `mega_download` varchar(200) DEFAULT NULL,
  `deskripsi` text DEFAULT NULL,
  `laporan` text DEFAULT NULL,
  `status` enum('ON','OFF') NOT NULL DEFAULT 'ON',
  `tgl` date DEFAULT NULL,
  `edisi` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `laporan_wp_1`
--

INSERT INTO `laporan_wp_1` (`id`, `judul`, `nama_gambar`, `kunci`, `url`, `url_x`, `url_preview`, `url_asli`, `url_asli_preview`, `harga`, `tags`, `mega_link`, `mega_download`, `deskripsi`, `laporan`, `status`, `tgl`, `edisi`) VALUES
(560, 'TechUp - Technology IT Solutions & Services Theme', '', 'techup-technologyit', '', '', 'https://closecrowds.com/themes/?theme=techup-technologyit', 'https://elements.envato.com/techup-technology-it-solutions-services-elementor--BJRFKUC', 'https://kits.pixel-show.com/techup/', 15, 'agency,app,app landing,business,cyber security,digital agency,digital business,hacker,saas,services,software company,solution,startup,technology,technology support', 'https://drive.google.com/file/d/1Xu_t5b2lopsjBFEHMHuX0FBtJvFvwSVn/view?usp=drivesdk', 'https://drive.google.com/file/d/13xlUDW0aGmb3rjq8UnvLNwp1oOyfhMgP/view?usp=drivesdk', '<p>echUp IT solutions &amp; Services Elementor templates suitable for your Digital Agency, IT Business, Consulting, SaaS &amp; Software, Startup website. You can use TechUp as a Creative way to showcase and promote your startup or running any digital marketing agency website.</p>\r\n\r\n<p>This Kit created with <strong>Elementor &ndash; the best page builder system</strong>, so you will not need any coding skills to use or configure templates. You will just do drag and dropping. Also, you can easily modify theme options easily, for doing it we have provided you with ultra-powerful options system.</p>\r\n\r\n<p><strong>Main Features</strong></p>\r\n\r\n<ul>\r\n	<li>Click Installation</li>\r\n	<li>Lifetime Free Updates</li>\r\n	<li>24/7 Customer Support</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'OFF', '2022-08-22', 1),
(561, 'Teqno - Tech Agency Theme', '', 'teqno-techagency', '', '', 'https://closecrowds.com/themes/?theme=teqno-techagency', 'https://elements.envato.com/teqno-tech-agency-elementor-template-kit-R35ZLPR', 'https://teqno.whmcsdes.com/', 15, 'agency,business,elementor,Elementor Kit,Elementor Template,host,hosting,saas,startup,support', 'https://drive.google.com/file/d/1TjzGI0yO_6H79jIkUJXkLIOgfHKeTO4G/view?usp=drivesdk', 'https://drive.google.com/file/d/13mexSRP5P21NrxN7dYQzPUMnpNYsoHBr/view?usp=drivesdk', '<p><strong>Teqno</strong></p>\r\n\r\n<p>Teqno is a creative Theme for Technology, Hosting, software, startup, and related products &amp; services. Teqno comes with various blocks that give its users real flexibility to create a dynamic, professional website in no time. It is 100% responsive and looks stunning on all types of screens and devices.</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>10 Content pages</li>\r\n	<li>Mobile Responsive Templates</li>\r\n	<li>Customizable fonts, colors, borders, backgrounds, gradient, etc.</li>\r\n	<li>Text and background gradient</li>\r\n	<li>Works well with all WordPress themes built on Elementor</li>\r\n	<li>Lightweight and Fast</li>\r\n	<li>All major browsers supported Chrome, Firefox, Safari, Opera, and Edge</li>\r\n	<li>Easy to use and customize with modern User Interface</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(562, 'Tflat NFT Portfolio Elementor Pro Full Site Theme', '', 'tflat-nftportfolio', '', '', 'https://closecrowds.com/themes/?theme=tflat-nftportfolio', 'https://elements.envato.com/tflat-nft-portfolio-elementor-pro-full-site-templa-W9DH4FN', 'https://tykit.rometheme.pro/tflat/', 19, 'artist,blockchain nft,cartoon,collectibles,crypto,crypto asset,digital,digital art,elementor,fintech,NFT,nft artist,NFT assets,portfolio', 'https://drive.google.com/file/d/1TNX9ZKRolu4wUu8H_WwL6l7H-6NnFBzh/view?usp=drivesdk', 'https://drive.google.com/file/d/1SMJX60JgYYj9deJQqbIkmPFxAAfdVe7Y/view?usp=drivesdk', '<p>Tflat is an Elementor Full Site Kit for quickly and easily creating a full Elementor Pro website for your Nft, Digatal Art &amp; Portfolio website. It is optiamized for the free Hello Elementor theme but can be used with most themes that support the Elementor page builder. Customize fonts and colors via the built in Elementor Theme Styles controls and load in your photos, logos and content using the visual drag and drop builder.</p>\r\n\r\n<p>This is not a WordPress theme. Themes contain page content for Elementor page builder. This kit has been optimized for use with the free Hello Elementor theme but may be used with most themes that support Elementor.</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>True no-code customization with drag and drop visual builder</li>\r\n	<li>Customize fonts and colors in one place or fine-tune on individual elements</li>\r\n	<li>Modern, professional design</li>\r\n	<li>Fast-loading</li>\r\n	<li>Works with most Elementor themes.</li>\r\n	<li>Full Elementor Pro Theme Builder globals</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(563, 'Uzino - Startup App Theme', '', 'uzino-startupapp', '', '', 'https://closecrowds.com/themes/?theme=uzino-startupapp', 'https://elements.envato.com/uzino-startup-app-elementor-template-kit-Q9VFTYX', 'https://surielementor.com/uzinokit/template-kit/home/', 19, 'agency,application,blog,bussines,creative,crowdfunder,elementor,ico,modern,portfolio,responsive,software,startup,technology', 'https://drive.google.com/file/d/1MxoT7zMCPsjGKObsCHLeE4VsCH_Z2jC3/view?usp=drivesdk', 'https://drive.google.com/file/d/1CtLaPz7GDh6JQs6OOgN6fyL32vtgDy34/view?usp=drivesdk', '<p><strong>Uzino | Premium Startup App Theme</strong></p>\r\n\r\n<p><strong>Uzino</strong> is built and suitable for Startup, App Landing, Software Landing website template, Uzino is exactly what every startup, digital business or app landing website needs. After importing the demo, you just need to change some information on the template to have a complete website. It is optimized for seo very well. All of the copyrighted images you can use for your website. You are looking for a WordPress SAAS Products, Startups &amp; Mobile Apps, this is the best choice</p>\r\n\r\n<p>Based on our super-flexible Framework, Consulty is by far a multi-purpose and responsive theme allowing you to set up your own web page without painfulness with its outstanding feature such as varied 02 Home Pages, 12+ inner Pages style, powerful options throughout each page, post, drag &amp; drop Page Builder, speed &amp; SEO optimized. Use Consulty to build any website.</p>\r\n\r\n<p><strong>Kit Key Features:</strong></p>\r\n\r\n<ul>\r\n	<li>One Click Demo Import</li>\r\n	<li>Includes 2 Home page</li>\r\n	<li>Unique and Modern Style.</li>\r\n	<li>Super Clear and Clean Layout</li>\r\n	<li>Awesome and Creative Design.</li>\r\n	<li>Lifetime Free Updates</li>\r\n	<li>24/7 Customer Support</li>\r\n	<li>Cross browser compatible</li>\r\n	<li>Built-in Header Footer</li>\r\n	<li>Support Post Widget</li>\r\n	<li>Support Carousel Slide Box ( Create sliders with anything )</li>\r\n	<li>Ultra Responsive and Retina Ready</li>\r\n	<li>Compatible with any WordPress theme</li>\r\n	<li>Optimized for search engines</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(564, 'Vanguard - Cyber Security Service Theme', '', 'vanguard-cybersecurity', '', '', 'https://closecrowds.com/themes/?theme=vanguard-cybersecurity', 'https://elements.envato.com/vanguard-cyber-security-service-elementor-template-G52ERDQ', 'https://demo.moxcreative.com/vanguard/template-kit/homepage/', 15, 'cybercrime,data security,digital agency,digital security,privacy,security,security agency,security company,security service,technology,unique,information technology,cybersecurity,Elementor Pro', 'https://drive.google.com/file/d/19OKIKAYSbnTmU6JHYCcf-kfSawzLkU6a/view?usp=drivesdk', 'https://drive.google.com/file/d/1fW35PGQzXCz4RW26u7xPts7yA7JrW2k9/view?usp=drivesdk', '<p>Vanguard is Elementor Theme for cyber tech and security service. This template layout has modern layout with unique design style and suitable for any business related to cyber tech and security service. You can easily build website for company that provide cyber tech or security service website. Just drag and drop, no coding required.</p>\r\n\r\n<p><strong>Layout Features :</strong></p>\r\n\r\n<ul>\r\n	<li>Modern and Professional design</li>\r\n	<li>Built with Elementor Pro</li>\r\n	<li>100% Responsive &amp; mobile-friendly</li>\r\n	<li>12+ pre-built templates</li>\r\n	<li>Easy to customize</li>\r\n	<li>Theme built with Elementor Hello Theme</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(565, 'veApp - Mobile App & Startup Theme', '', 'veapp-mobileapp', '', '', 'https://closecrowds.com/themes/?theme=veapp-mobileapp', 'https://elements.envato.com/veapp-mobile-app-startup-elementor-template-kit-XRV77CF', 'https://kits.pixel-show.com/veapp/', 15, 'agency,app,app landing,app landing page,app landing template,app template,digital landing page,elementor,landing page,mobile,product landing,product landing page,software,startup', 'https://drive.google.com/file/d/16lvuCzjkOXWW_7g_3l2hUufMRelG4jBI/view?usp=drivesdk', 'https://drive.google.com/file/d/1-_RYeSKbR6_FVMxd_nlH0S6VCAa8kHNA/view?usp=drivesdk', '<p><strong>veApp</strong> is a creative &amp; unique Elementor templates based on latest technology. All files are clearly organized we believe it will be easy to use and edit them. This theme is well organized and very easy to customize. Its easy to use and navigate as well. Compatible with Desktop, Laptop, table, mobile or any device. Suitable for anyone who is looking for <strong>app, app landing, app landing page, app landing template, App Showcase, app store, app template, app website, clean app landing, creative app landing page, landing page, mobile app landing page &amp; modern app Landing</strong>.</p>\r\n\r\n<p><strong>Main Features:</strong></p>\r\n\r\n<ul>\r\n	<li>11 Elementor Templates</li>\r\n	<li>True no-code customization with drag and drop visual builder</li>\r\n	<li>Customize fonts and colors in one place or fine-tune on individual elements</li>\r\n	<li>Modern, professional design</li>\r\n	<li>Fast-loading</li>\r\n	<li>Works with most Elementor themes.</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(566, 'Vibranet - Broadband & Internet Service Provider Theme', '', 'vibranet-broadbandinternet', '', '', 'https://closecrowds.com/themes/?theme=vibranet-broadbandinternet', 'https://elements.envato.com/vibranet-broadband-internet-service-provider-eleme-B5S8TQR', 'https://kit.baliniz.com/vibranet/', 19, 'agency,broadband,business,company,connection,internet,internet provider,internet service provider,satellite,technology,telecom,telecommunication,television,wifi,isp', 'https://drive.google.com/file/d/13OgA4ch1PZfGboerX2nhzlLC1tgq8V_v/view?usp=drivesdk', 'https://drive.google.com/file/d/1dMaR4NihyfSX7p5eHbB2fMfoYSB1xNhp/view?usp=drivesdk', '<p>Vibranet is a modern Elementor Theme to create a pro-level and functional website for Internet Service Providers, Broadband, Telecom, Cable TV Providers, Telecommunications companies, and as well as it fits also for Technology, Startup, and any kind of IT-related business.</p>\r\n\r\n<p>This Theme includes carefully crafted 16+ Elementor templates with a 100% responsive layout &amp; retina-ready. You can build your professional, modern, and functional WordPress website just a click away without any single line of coding!</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Using Free Plugins (Elementor Pro is not required)</li>\r\n	<li>Modern &amp; Clean Design</li>\r\n	<li>16+ Ready to use templates</li>\r\n	<li>Fully Responsive Layout</li>\r\n	<li>Retina Ready</li>\r\n	<li>Fully Customizable</li>\r\n	<li>Cross Browser Compatibility: Chrome, Firefox, Safari, Opera</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(567, 'Virtu - Tech & Software Company Elementor Template kit', '', NULL, NULL, NULL, 'OFF', NULL, 'http://tykit.rometheme.pro/virtu/?storefront=envato-elements', NULL, NULL, 'https://drive.google.com/file/d/1xsWVxJGPSclbl3qrgNIcoXgaIQq1EGZd/view?usp=drivesdk', 'https://drive.google.com/file/d/1k_oBE2HDKLhkJAjFA1gIQ4s5uRjxnsFY/view?usp=drivesdk', NULL, NULL, 'ON', '2022-08-22', 1),
(568, 'Vitech - Technology & IT Solution Theme', '', 'vitech-technology', '', '', 'https://closecrowds.com/themes/?theme=vitech-technology', 'https://elements.envato.com/vitech-technology-it-solution-elementor-template-k-NVTNCBQ', 'https://templatekit.jegtheme.com/vitech/', 15, 'agency,business,company,corporate,digital,elementor,information technology,modern,solution,startup,technology,template,template kit,website,wordpress', 'https://drive.google.com/file/d/1fX0x_YcjpWPW_FTFZgtYgDbWgEjCPiyI/view?usp=drivesdk', 'https://drive.google.com/file/d/10h-tFSg3QN8Apz0hZGKp8Zq6vCzEgiCb/view?usp=drivesdk', '<p>Vitech is a modern and clean Technology &amp; IT solutions Elementor Theme to create a responsive and fully functional WordPress based website for Tech Startup, Digital Agency, Virtual Reality, Augmented Reality, IT Services, Software Solution, or any technology related businesses without a single line of code!</p>\r\n\r\n<p>This Theme includes stunning carefully crafted 18+ stunning templates, you can build your professional-looking company business website just a click away.</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Using Free Plugins (Elementor Pro is not required)</li>\r\n	<li>Modern &amp; Clean Design</li>\r\n	<li>18+ Ready to use templates</li>\r\n	<li>Fully Responsive Layout</li>\r\n	<li>Retina Ready</li>\r\n	<li>Fully Customizable</li>\r\n	<li>Cross Browser Compatibility: Chrome, Firefox, Safari, Opera</li>\r\n</ul>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1),
(569, 'Wartel - Home Wifi & Internet Provider Services Theme', '', 'wartel-homewifi', '', '', 'https://closecrowds.com/themes/?theme=wartel-homewifi', 'https://elements.envato.com/wartel-home-wifi-internet-provider-services-elemen-2DDKJKJ', 'https://gajean.com/wartel/template-kit/home-1/', 19, 'connection,home wifi,internet,provider,red,isp,internet service provider,Internet Cafe,cloud services', 'https://drive.google.com/file/d/1sP5Da5EQwMNqdM7A2nwD2b1nUV0nSXmr/view?usp=drivesdk', 'https://drive.google.com/file/d/1m0nnnpPK6zztRUzJqdwzZvhd3NXUcrra/view?usp=drivesdk', '<p>Wartel - Home Wifi &amp; Internet Provider Services Elementor Theme is a collection of layouts for the Elementor page builder WordPress plugin, designed for use with Elementor Pro Version for a clean Design. It works with most themes and is optimized for use with the free Hello Elementor theme.</p>\r\n', 'array(\r\n        \"id\" 		 => \"\",\r\n        \"url\" 		 => \"\",\r\n        \"purchase\" 	 => \"\",\r\n        \"responsive\" => \"yes\",\r\n        \"type\"       => \"wordpress\",\r\n        \"thumb\"      => \"\"\r\n    ),', 'ON', '2022-08-22', 1);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
